from enum import Enum


class OfferType(str, Enum):
    # General services
    MAINTENANCE = "MAINTENANCE"  # Regular servicing, inspections
    REPAIR = "REPAIR"  # General mechanical repairs
    DIAGNOSTICS = "DIAGNOSTICS"  # Computer & manual diagnostics

    # Engine & drivetrain
    ENGINE_REPAIR = "ENGINE_REPAIR"
    TRANSMISSION_REPAIR = "TRANSMISSION_REPAIR"
    CLUTCH_REPAIR = "CLUTCH_REPAIR"
    TIMING_BELT_REPLACEMENT = "TIMING_BELT_REPLACEMENT"

    # Brakes & suspension
    BRAKE_SERVICE = "BRAKE_SERVICE"  # Pads, discs, fluid
    SUSPENSION_REPAIR = "SUSPENSION_REPAIR"  # Shocks, struts, bushings
    STEERING_REPAIR = "STEERING_REPAIR"

    # Electrical & electronics
    ELECTRICAL = "ELECTRICAL"
    BATTERY_SERVICE = "BATTERY_SERVICE"
    ALTERNATOR_REPAIR = "ALTERNATOR_REPAIR"
    STARTER_REPAIR = "STARTER_REPAIR"
    LIGHTING_REPAIR = "LIGHTING_REPAIR"
    ECU_PROGRAMMING = "ECU_PROGRAMMING"

    # Fluids & filters
    OIL_CHANGE = "OIL_CHANGE"
    FILTER_REPLACEMENT = "FILTER_REPLACEMENT"
    COOLANT_SERVICE = "COOLANT_SERVICE"
    BRAKE_FLUID_SERVICE = "BRAKE_FLUID_SERVICE"
    TRANSMISSION_FLUID_SERVICE = "TRANSMISSION_FLUID_SERVICE"

    # Tires & wheels
    TIRE_CHANGE = "TIRE_CHANGE"
    TIRE_BALANCING = "TIRE_BALANCING"
    WHEEL_ALIGNMENT = "WHEEL_ALIGNMENT"
    PUNCTURE_REPAIR = "PUNCTURE_REPAIR"

    # Exhaust & emissions
    EXHAUST_REPAIR = "EXHAUST_REPAIR"
    EMISSIONS_SERVICE = "EMISSIONS_SERVICE"
    CATALYTIC_CONVERTER_REPAIR = "CATALYTIC_CONVERTER_REPAIR"

    # Heating & air conditioning
    AC_SERVICE = "AC_SERVICE"
    AC_REPAIR = "AC_REPAIR"
    HEATING_REPAIR = "HEATING_REPAIR"

    # Body & exterior
    BODY_WORK = "BODY_WORK"
    PAINTING = "PAINTING"
    DENT_REMOVAL = "DENT_REMOVAL"
    WINDSHIELD_REPLACEMENT = "WINDSHIELD_REPLACEMENT"
    RUST_REPAIR = "RUST_REPAIR"

    # Interior & comfort
    INTERIOR_REPAIR = "INTERIOR_REPAIR"
    UPHOLSTERY_REPAIR = "UPHOLSTERY_REPAIR"
    WINDOW_MECHANISM_REPAIR = "WINDOW_MECHANISM_REPAIR"

    # Safety & inspection
    PRE_PURCHASE_INSPECTION = "PRE_PURCHASE_INSPECTION"
    SAFETY_INSPECTION = "SAFETY_INSPECTION"

    # Other services
    CAR_WASH = "CAR_WASH"
    DETAILING = "DETAILING"
    TOWING = "TOWING"
