"""car_model - body type as enum

Revision ID: 25296b3bb7dd
Revises: c11e0aa5b9b9
Create Date: 2026-06-01 02:42:44.140229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25296b3bb7dd'
down_revision: Union[str, Sequence[str], None] = 'c11e0aa5b9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
