"""offer group update

Revision ID: 26a457e9d66c
Revises: 8a6f0f4bff56
Create Date: 2026-05-26 01:28:35.420201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a457e9d66c'
down_revision: Union[str, Sequence[str], None] = '8a6f0f4bff56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop FK constraint on user_car_relation FIRST, before dropping car_types
    op.drop_constraint(op.f('user_car_relation_car_type_id_fkey'), 'user_car_relation', type_='foreignkey')

    # 2. Create new car_model table
    op.create_table('car_model',
    sa.Column('car_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_brand_id', sa.Integer(), nullable=False),
    sa.Column('car_type_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_brand_id'], ['car_brands.car_brand_id'], ),
    sa.PrimaryKeyConstraint('car_type_id'),
    sa.UniqueConstraint('car_type_name')
    )
    op.create_index(op.f('ix_car_model_car_brand_id'), 'car_model', ['car_brand_id'], unique=False)

    # 3. Drop old car_types table (FK already removed, safe to drop now)
    op.drop_index(op.f('ix_car_types_car_brand_id'), table_name='car_types')
    op.drop_table('car_types')

    # 4. Recreate FK on user_car_relation pointing to new car_model table
    op.create_foreign_key(None, 'user_car_relation', 'car_model', ['car_type_id'], ['car_type_id'])

    # 5. Rest of the operations
    op.create_table('service_offer_group',
    sa.Column('service_offer_group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('offer_group_code', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('service_offer_group_id'),
    sa.UniqueConstraint('service_id', 'offer_group_code', name='unique_service_offer_group_code')
    )
    op.create_index(op.f('ix_service_offer_group_description'), 'service_offer_group', ['description'], unique=False)
    op.create_index(op.f('ix_service_offer_group_offer_group_code'), 'service_offer_group', ['offer_group_code'], unique=False)
    op.create_index(op.f('ix_service_offer_group_service_id'), 'service_offer_group', ['service_id'], unique=False)
    op.drop_table('ev_engines')
    op.drop_table('ice_engines')
    op.execute("CREATE TYPE country AS ENUM ('SLOVAKIA', 'CZECHIA', 'AUSTRIA', 'POLAND', 'HUNGARY')")

    op.add_column('car_brands', sa.Column('country', sa.Enum('SLOVAKIA', 'CZECHIA', 'AUSTRIA', 'POLAND', 'HUNGARY', name='country', length=20), nullable=False))
    op.create_index(op.f('ix_car_brands_country'), 'car_brands', ['country'], unique=False)
    op.drop_column('car_brands', 'logo_extension')
    op.add_column('engine_types', sa.Column('engine_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'engine_types', ['engine_code'])
    op.drop_column('engine_types', 'power_output')
    op.drop_column('engine_types', 'torque_nm')
    op.drop_column('engine_types', 'engine_type')
    op.add_column('offer_group', sa.Column('group_code', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_offer_group_group_code'), 'offer_group', ['group_code'], unique=True)
    op.add_column('offers', sa.Column('service_offer_group_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_index(op.f('ix_offers_offer_group_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_service_id'), table_name='offers')
    op.drop_constraint(op.f('unique_offer_service_id'), 'offers', type_='unique')
    op.create_index(op.f('ix_offers_service_offer_group_id'), 'offers', ['service_offer_group_id'], unique=False)
    op.drop_constraint(op.f('offers_offer_group_id_fkey'), 'offers', type_='foreignkey')
    op.drop_constraint(op.f('offers_service_id_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'service_offer_group', ['service_offer_group_id'], ['service_offer_group_id'])
    op.drop_column('offers', 'service_id')
    op.drop_column('offers', 'offer_group_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_car_relation', type_='foreignkey')
    op.create_foreign_key(op.f('user_car_relation_car_type_id_fkey'), 'user_car_relation', 'car_types', ['car_type_id'], ['car_type_id'])
    op.add_column('offers', sa.Column('offer_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_service_id_fkey'), 'offers', 'services', ['service_id'], ['service_id'])
    op.create_foreign_key(op.f('offers_offer_group_id_fkey'), 'offers', 'offer_group', ['offer_group_id'], ['offer_group_id'])
    op.drop_index(op.f('ix_offers_service_offer_group_id'), table_name='offers')
    op.create_unique_constraint(op.f('unique_offer_service_id'), 'offers', ['offer_id', 'service_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_offers_service_id'), 'offers', ['service_id'], unique=False)
    op.create_index(op.f('ix_offers_offer_group_id'), 'offers', ['offer_group_id'], unique=False)
    op.drop_column('offers', 'service_offer_group_id')
    op.drop_index(op.f('ix_offer_group_group_code'), table_name='offer_group')
    op.drop_column('offer_group', 'group_code')
    op.add_column('engine_types', sa.Column('engine_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('engine_types', sa.Column('torque_nm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('engine_types', sa.Column('power_output', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'engine_types', type_='unique')
    op.alter_column('engine_types', 'engine_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('engine_types', 'engine_code')
    op.add_column('car_brands', sa.Column('logo_extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_car_brands_country'), table_name='car_brands')
    op.drop_column('car_brands', 'country')
    op.create_table('ice_engines',
    sa.Column('engine_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('engine_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cylinder_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], name=op.f('ice_engines_engine_id_fkey')),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('ice_engines_pkey'))
    )
    op.create_table('car_types',
    sa.Column('car_type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_type_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('car_brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_brand_id'], ['car_brands.car_brand_id'], name=op.f('car_types_car_brand_id_fkey')),
    sa.PrimaryKeyConstraint('car_type_id', name=op.f('car_types_pkey')),
    sa.UniqueConstraint('car_type_name', name=op.f('car_types_car_type_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_car_types_car_brand_id'), 'car_types', ['car_brand_id'], unique=False)
    op.create_table('ev_engines',
    sa.Column('engine_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('battery_capacity_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('charging_standard', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('electric_range_km', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], name=op.f('ev_engines_engine_id_fkey')),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('ev_engines_pkey'))
    )
    op.drop_index(op.f('ix_service_offer_group_service_id'), table_name='service_offer_group')
    op.drop_index(op.f('ix_service_offer_group_offer_group_code'), table_name='service_offer_group')
    op.drop_index(op.f('ix_service_offer_group_description'), table_name='service_offer_group')
    op.drop_table('service_offer_group')
    op.drop_index(op.f('ix_car_model_car_brand_id'), table_name='car_model')
    op.drop_table('car_model')
    # ### end Alembic commands ###
