"""description models

Revision ID: 34b0b8e51d36
Revises: fd68bcd05132
Create Date: 2026-04-13 00:38:50.891288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b0b8e51d36'
down_revision: Union[str, Sequence[str], None] = 'fd68bcd05132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_description',
    sa.Column('description_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('language_code', sa.Enum('EN', 'SK', 'CZ', 'DE', 'HU', 'PL', name='languagecode', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('description_id', 'organization_id')
    )
    op.create_table('service_description',
    sa.Column('description_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('language_code', sa.Enum('EN', 'SK', 'CZ', 'DE', 'HU', 'PL', name='languagecode', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('description_id', 'service_id')
    )
    op.create_table('offer_description',
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('language_code', sa.Enum('EN', 'SK', 'CZ', 'DE', 'HU', 'PL', name='languagecode', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.PrimaryKeyConstraint('description_id')
    )
    op.create_index(op.f('ix_offer_description_offer_id'), 'offer_description', ['offer_id'], unique=False)
    op.drop_index(op.f('ix_offer_car_compatibility_car_type_id'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_created_at'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_engine_id'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_offer_id'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_updated_at'), table_name='offer_car_compatibility')
    op.drop_table('offer_car_compatibility')
    op.drop_column('organization', 'description')
    op.drop_column('services', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('offer_car_compatibility',
    sa.Column('offer_car_compatibility_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('car_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_types.car_type_id'], name=op.f('offer_car_compatibility_car_type_id_fkey')),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], name=op.f('offer_car_compatibility_engine_id_fkey')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name=op.f('offer_car_compatibility_offer_id_fkey')),
    sa.PrimaryKeyConstraint('offer_car_compatibility_id', name=op.f('offer_car_compatibility_pkey')),
    sa.UniqueConstraint('offer_id', 'car_type_id', 'engine_id', name=op.f('uq_offer_car_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_offer_car_compatibility_updated_at'), 'offer_car_compatibility', ['updated_at'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_offer_id'), 'offer_car_compatibility', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_engine_id'), 'offer_car_compatibility', ['engine_id'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_created_at'), 'offer_car_compatibility', ['created_at'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_car_type_id'), 'offer_car_compatibility', ['car_type_id'], unique=False)
    op.drop_index(op.f('ix_offer_description_offer_id'), table_name='offer_description')
    op.drop_table('offer_description')
    op.drop_table('service_description')
    op.drop_table('organization_description')
    # ### end Alembic commands ###
