"""engine model - native enum code

Revision ID: 4363361e4b4f
Revises: 26a457e9d66c
Create Date: 2026-05-27 02:25:38.488660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4363361e4b4f'
down_revision: Union[str, Sequence[str], None] = '26a457e9d66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_engine_relation',
    sa.Column('car_engine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('car_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_model.car_type_id'], ),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], ),
    sa.PrimaryKeyConstraint('car_engine_id')
    )
    op.create_index(op.f('ix_car_engine_relation_car_type_id'), 'car_engine_relation', ['car_type_id'], unique=False)
    op.create_index(op.f('ix_car_engine_relation_engine_id'), 'car_engine_relation', ['engine_id'], unique=False)
    # 1. Drop the default (old SERIAL sequence default)
    op.alter_column('engine_types', 'engine_id', server_default=None)

    # 2. Add IDENTITY
    op.execute("""
        ALTER TABLE engine_types 
        ALTER COLUMN engine_id ADD GENERATED ALWAYS AS IDENTITY
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engine_types', 'engine_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_car_engine_relation_engine_id'), table_name='car_engine_relation')
    op.drop_index(op.f('ix_car_engine_relation_car_type_id'), table_name='car_engine_relation')
    op.drop_table('car_engine_relation')
    # ### end Alembic commands ###
