"""engine model - polymorphic identity

Revision ID: 4790c333a3b3
Revises: f16c6903bb8b
Create Date: 2026-04-09 00:23:43.718557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4790c333a3b3'
down_revision: Union[str, Sequence[str], None] = 'f16c6903bb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_engines',
    sa.Column('engine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('cylinder_count', sa.Integer(), nullable=False),
    sa.Column('charging_standard', sa.Enum('TYPE1', 'TYPE2', 'CCS1', 'CCS2', 'CHADEMO', 'GBT', 'TESLA', name='chargingstandard', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], ),
    sa.PrimaryKeyConstraint('engine_id')
    )
    op.create_table('ice_engines',
    sa.Column('engine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_volume', sa.Float(), nullable=False),
    sa.Column('cylinder_count', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', name='fueltype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engine_types.engine_id'], ),
    sa.PrimaryKeyConstraint('engine_id')
    )
    op.add_column('engine_types', sa.Column('power_output', sa.Float(), nullable=True))
    op.add_column('engine_types', sa.Column('torque_nm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine_types', 'torque_nm')
    op.drop_column('engine_types', 'power_output')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('ice_engines')
    op.drop_table('ev_engines')
    # ### end Alembic commands ###
