"""language model

Revision ID: 4dc677da8384
Revises: e7c0d0956457
Create Date: 2026-03-09 03:02:53.990648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc677da8384'
down_revision: Union[str, Sequence[str], None] = 'e7c0d0956457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_type_translations',
    sa.Column('offer_type_translation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('language_code', sa.Enum('EN', 'SK', 'CZ', 'DE', 'HU', 'PL', name='languagecode', native_enum=False, length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('offer_type_translation_id'),
    sa.UniqueConstraint('code', 'language_code', name='offer_type_translation_codes')
    )
    op.create_index(op.f('ix_offer_type_translations_code'), 'offer_type_translations', ['code'], unique=False)
    op.create_index(op.f('ix_offer_type_translations_language_code'), 'offer_type_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_offer_type_translations_name'), 'offer_type_translations', ['name'], unique=False)
    op.create_table('relation_translated_offer',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('offer_type_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.ForeignKeyConstraint(['offer_type_translation_id'], ['offer_type_translations.offer_type_translation_id'], ),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('offer_id', 'offer_type_translation_id', name='uq_offer_translation')
    )
    op.create_index(op.f('ix_relation_translated_offer_offer_id'), 'relation_translated_offer', ['offer_id'], unique=False)
    op.create_index(op.f('ix_relation_translated_offer_offer_type_translation_id'), 'relation_translated_offer', ['offer_type_translation_id'], unique=False)
    op.drop_index(op.f('ix_offers_offer_type'), table_name='offers')
    op.drop_column('offers', 'description')
    op.drop_column('offers', 'offer_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('offer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_offers_offer_type'), 'offers', ['offer_type'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_relation_translated_offer_offer_type_translation_id'), table_name='relation_translated_offer')
    op.drop_index(op.f('ix_relation_translated_offer_offer_id'), table_name='relation_translated_offer')
    op.drop_table('relation_translated_offer')
    op.drop_index(op.f('ix_offer_type_translations_name'), table_name='offer_type_translations')
    op.drop_index(op.f('ix_offer_type_translations_language_code'), table_name='offer_type_translations')
    op.drop_index(op.f('ix_offer_type_translations_code'), table_name='offer_type_translations')
    op.drop_table('offer_type_translations')
    # ### end Alembic commands ###
