"""new model offer_car_compatibility

Revision ID: 4fdbdeaddc3b
Revises: 91f0d35e22a9
Create Date: 2026-01-02 21:26:29.032777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdbdeaddc3b'
down_revision: Union[str, Sequence[str], None] = '91f0d35e22a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_car_compatibility',
    sa.Column('offer_car_compatibility_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('offer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('car_type', sa.Enum('SEDAN', 'HATCHBACK', 'COUPE', 'CONVERTIBLE', 'WAGON', 'LIFTBACK', 'SPORTS', 'SUPER_CAR', 'LUXURY', 'CLASSIC', 'SUV', 'CROSSOVER', 'OFF_ROAD', 'PICKUP', 'TRUCK', 'VAN', 'MINIVAN', 'BUS', 'BOX_TRUCK', 'ELECTRIC', 'HYBRID', 'PLUG_IN_HYBRID', 'HYDROGEN', 'TAXI', 'POLICE', 'AMBULANCE', 'FIRE_TRUCK', 'MILITARY', 'MOTORCYCLE', 'SCOOTER', 'ALL', name='cartype', native_enum=False, length=50), nullable=False),
    sa.Column('car_brand', sa.Enum('HONDA', 'TOYOTA', 'FORD', 'CHEVROLET', 'BMW', 'MERCEDES_BENZ', 'AUDI', 'VOLKSWAGEN', 'NISSAN', 'HYUNDAI', 'KIA', 'SUBARU', 'MAZDA', 'JEEP', 'LEXUS', 'DODGE', 'JAGUAR', 'LAND_ROVER', 'TESLA', 'VOLVO', 'FIAT', 'ALFA_ROMEO', 'MITSUBISHI', 'RENAULT', 'PEUGEOT', 'CITROEN', 'SUZUKI', 'INFINITI', 'ACURA', 'CADILLAC', 'BUICK', 'GMC', 'CHRYSLER', 'RAM', 'MINI', 'SMART', 'SAAB', 'SKODA', 'SEAT', 'LADA', 'TATA', 'MAHINDRA', 'GREAT_WALL', 'GEELY', 'LIFAN', 'BYD', 'CHERY', 'HAFEI', 'JAC', 'ALL', name='carbrands', native_enum=False, length=50), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.PrimaryKeyConstraint('offer_car_compatibility_id'),
    sa.UniqueConstraint('offer_id', 'car_type', 'car_brand', name='uq_offer_car_type_brand')
    )
    op.create_index(op.f('ix_offer_car_compatibility_car_brand'), 'offer_car_compatibility', ['car_brand'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_car_type'), 'offer_car_compatibility', ['car_type'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_offer_id'), 'offer_car_compatibility', ['offer_id'], unique=False)
    op.drop_index(op.f('ix_offers_car_type'), table_name='offers')
    op.drop_column('offers', 'car_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('car_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_offers_car_type'), 'offers', ['car_type'], unique=False)
    op.drop_index(op.f('ix_offer_car_compatibility_offer_id'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_car_type'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_car_brand'), table_name='offer_car_compatibility')
    op.drop_table('offer_car_compatibility')
    # ### end Alembic commands ###
