"""user setup

Revision ID: 68a0a5b326f7
Revises: 8542bc18aff1
Create Date: 2026-04-06 15:42:04.867413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a0a5b326f7'
down_revision: Union[str, Sequence[str], None] = '8542bc18aff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setup',
    sa.Column('user_setup_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_setup_id')
    )
    op.create_table('user_car_relation',
    sa.Column('user_car_relation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('car_type_id', sa.Integer(), nullable=False),
    sa.Column('engine_type_id', sa.Integer(), nullable=False),
    sa.Column('user_setup_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('car_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_types.car_type_id'], ),
    sa.ForeignKeyConstraint(['engine_type_id'], ['engine_types.engine_type_id'], ),
    sa.ForeignKeyConstraint(['user_setup_id'], ['user_setup.user_setup_id'], ),
    sa.PrimaryKeyConstraint('user_car_relation_id'),
    sa.UniqueConstraint('user_id', 'car_type_id', name='uq_user_car_relation_id')
    )
    op.create_index(op.f('ix_user_car_relation_car_type_id'), 'user_car_relation', ['car_type_id'], unique=False)
    op.create_index(op.f('ix_user_car_relation_engine_type_id'), 'user_car_relation', ['engine_type_id'], unique=False)
    op.create_index(op.f('ix_user_car_relation_user_setup_id'), 'user_car_relation', ['user_setup_id'], unique=False)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'USER'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_car_relation_user_setup_id'), table_name='user_car_relation')
    op.drop_index(op.f('ix_user_car_relation_engine_type_id'), table_name='user_car_relation')
    op.drop_index(op.f('ix_user_car_relation_car_type_id'), table_name='user_car_relation')
    op.drop_table('user_car_relation')
    op.drop_table('user_setup')
    # ### end Alembic commands ###
