"""car brand - logo extension

Revision ID: 6b9d8ffc0e26
Revises: 4f9075cb89ae
Create Date: 2026-04-07 00:21:02.434787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9d8ffc0e26'
down_revision: Union[str, Sequence[str], None] = '4f9075cb89ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_brands', sa.Column('logo_extension', sa.String(), nullable=False))
    op.add_column('engine_types', sa.Column('engine_type', sa.Enum('ELECTRIC', 'HYBRID', 'PETROL', 'DIESEL', name='enginetype', native_enum=False, length=20), nullable=False))
    op.add_column('user_car_relation', sa.Column('created_at', sa.Integer(), nullable=False))
    op.add_column('user_car_relation', sa.Column('updated_at', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_car_relation', 'updated_at')
    op.drop_column('user_car_relation', 'created_at')
    op.drop_column('engine_types', 'engine_type')
    op.drop_column('car_brands', 'logo_extension')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
