"""first init

Revision ID: 78ff8f4f0d7c
Revises:
Create Date: 2025-12-24 16:26:44.889267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78ff8f4f0d7c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "country",
            sa.Enum(
                "SLOVAKIA", "CZECHIA", "AUSTRIA", "POLAND", "HUNGARY", name="country", native_enum=False, length=50
            ),
            nullable=False,
        ),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("house_number", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("identification_number", sa.String(), nullable=False),
        sa.Column("owner", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("organization_id"),
        sa.UniqueConstraint("name", "identification_number", name="uq_service_identification_number_name"),
        sa.UniqueConstraint("name", "owner", name="uq_owner_organization_name"),
        sa.UniqueConstraint("name", "postal_code", name="uq_postal_code_name"),
    )
    op.create_index(op.f("ix_organization_city"), "organization", ["city"], unique=False)
    op.create_index(op.f("ix_organization_country"), "organization", ["country"], unique=False)
    op.create_index(op.f("ix_organization_created_at"), "organization", ["created_at"], unique=False)
    op.create_index(op.f("ix_organization_house_number"), "organization", ["house_number"], unique=False)
    op.create_index(
        op.f("ix_organization_identification_number"), "organization", ["identification_number"], unique=False
    )
    op.create_index(op.f("ix_organization_name"), "organization", ["name"], unique=False)
    op.create_index(op.f("ix_organization_owner"), "organization", ["owner"], unique=False)
    op.create_index(op.f("ix_organization_postal_code"), "organization", ["postal_code"], unique=False)
    op.create_index(op.f("ix_organization_street"), "organization", ["street"], unique=False)
    op.create_index(op.f("ix_organization_updated_at"), "organization", ["updated_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MODERATOR", "USER", "MASTER", name="roles", native_enum=False, length=50),
            server_default="USER",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "services",
        sa.Column("service_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "country",
            sa.Enum(
                "SLOVAKIA", "CZECHIA", "AUSTRIA", "POLAND", "HUNGARY", name="country", native_enum=False, length=50
            ),
            nullable=False,
        ),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("house_number", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("identification_number", sa.String(), nullable=False),
        sa.Column("owner", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.organization_id"],
        ),
        sa.PrimaryKeyConstraint("service_id"),
        sa.UniqueConstraint("name", "identification_number", name="uq_identification_number_name"),
    )
    op.create_index(op.f("ix_services_city"), "services", ["city"], unique=False)
    op.create_index(op.f("ix_services_country"), "services", ["country"], unique=False)
    op.create_index(op.f("ix_services_created_at"), "services", ["created_at"], unique=False)
    op.create_index(op.f("ix_services_email"), "services", ["email"], unique=False)
    op.create_index(op.f("ix_services_house_number"), "services", ["house_number"], unique=False)
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=False)
    op.create_index(op.f("ix_services_organization_id"), "services", ["organization_id"], unique=False)
    op.create_index(op.f("ix_services_owner"), "services", ["owner"], unique=False)
    op.create_index(op.f("ix_services_phone_number"), "services", ["phone_number"], unique=False)
    op.create_index(op.f("ix_services_postal_code"), "services", ["postal_code"], unique=False)
    op.create_index(op.f("ix_services_street"), "services", ["street"], unique=False)
    op.create_index(op.f("ix_services_updated_at"), "services", ["updated_at"], unique=False)
    op.create_table(
        "offers",
        sa.Column("offer_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "MAINTENANCE",
                "REPAIR",
                "DIAGNOSTICS",
                "ELECTRICAL",
                "BODY_WORK",
                name="offertype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "car_type",
            sa.Enum(
                "CLASSIC",
                "SPORTS",
                "ELECTRICAL",
                "SUV",
                "TRUCK",
                "HYBRID",
                "BUS",
                name="cartype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.Enum("USD", "EUR", "PLN", "GBP", "CZK", "HUF", name="currency", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("base_price", sa.Float(), nullable=False),
        sa.Column("sale", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.service_id"],
        ),
        sa.PrimaryKeyConstraint("offer_id"),
        sa.UniqueConstraint("service_id", "name", "car_type", name="uq_service_id_name_and_car_type"),
    )
    op.create_index(op.f("ix_offers_base_price"), "offers", ["base_price"], unique=False)
    op.create_index(op.f("ix_offers_car_type"), "offers", ["car_type"], unique=False)
    op.create_index(op.f("ix_offers_created_at"), "offers", ["created_at"], unique=False)
    op.create_index(op.f("ix_offers_currency"), "offers", ["currency"], unique=False)
    op.create_index(
        op.f("ix_offers_estimated_duration_minutes"), "offers", ["estimated_duration_minutes"], unique=False
    )
    op.create_index(op.f("ix_offers_name"), "offers", ["name"], unique=False)
    op.create_index(op.f("ix_offers_sale"), "offers", ["sale"], unique=False)
    op.create_index(op.f("ix_offers_service_id"), "offers", ["service_id"], unique=False)
    op.create_index(op.f("ix_offers_updated_at"), "offers", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_offers_updated_at"), table_name="offers")
    op.drop_index(op.f("ix_offers_service_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_sale"), table_name="offers")
    op.drop_index(op.f("ix_offers_name"), table_name="offers")
    op.drop_index(op.f("ix_offers_estimated_duration_minutes"), table_name="offers")
    op.drop_index(op.f("ix_offers_currency"), table_name="offers")
    op.drop_index(op.f("ix_offers_created_at"), table_name="offers")
    op.drop_index(op.f("ix_offers_car_type"), table_name="offers")
    op.drop_index(op.f("ix_offers_base_price"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_services_updated_at"), table_name="services")
    op.drop_index(op.f("ix_services_street"), table_name="services")
    op.drop_index(op.f("ix_services_postal_code"), table_name="services")
    op.drop_index(op.f("ix_services_phone_number"), table_name="services")
    op.drop_index(op.f("ix_services_owner"), table_name="services")
    op.drop_index(op.f("ix_services_organization_id"), table_name="services")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_index(op.f("ix_services_house_number"), table_name="services")
    op.drop_index(op.f("ix_services_email"), table_name="services")
    op.drop_index(op.f("ix_services_created_at"), table_name="services")
    op.drop_index(op.f("ix_services_country"), table_name="services")
    op.drop_index(op.f("ix_services_city"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organization_updated_at"), table_name="organization")
    op.drop_index(op.f("ix_organization_street"), table_name="organization")
    op.drop_index(op.f("ix_organization_postal_code"), table_name="organization")
    op.drop_index(op.f("ix_organization_owner"), table_name="organization")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_index(op.f("ix_organization_identification_number"), table_name="organization")
    op.drop_index(op.f("ix_organization_house_number"), table_name="organization")
    op.drop_index(op.f("ix_organization_created_at"), table_name="organization")
    op.drop_index(op.f("ix_organization_country"), table_name="organization")
    op.drop_index(op.f("ix_organization_city"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
