"""service model - social media

Revision ID: 803495c725c8
Revises: 34b0b8e51d36
Create Date: 2026-04-13 01:36:07.889507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803495c725c8'
down_revision: Union[str, Sequence[str], None] = '34b0b8e51d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('services', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('services', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('services', sa.Column('website', sa.String(), nullable=True))
    op.create_index(op.f('ix_services_facebook'), 'services', ['facebook'], unique=False)
    op.create_index(op.f('ix_services_instagram'), 'services', ['instagram'], unique=False)
    op.create_index(op.f('ix_services_twitter'), 'services', ['twitter'], unique=False)
    op.create_index(op.f('ix_services_website'), 'services', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_website'), table_name='services')
    op.drop_index(op.f('ix_services_twitter'), table_name='services')
    op.drop_index(op.f('ix_services_instagram'), table_name='services')
    op.drop_index(op.f('ix_services_facebook'), table_name='services')
    op.drop_column('services', 'website')
    op.drop_column('services', 'twitter')
    op.drop_column('services', 'facebook')
    op.drop_column('services', 'instagram')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
