"""offer schema - updated

Revision ID: 8a6f0f4bff56
Revises: 5f7050dc7d79
Create Date: 2026-05-11 23:58:12.615082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6f0f4bff56'
down_revision: Union[str, Sequence[str], None] = '5f7050dc7d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_group',
    sa.Column('offer_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('create_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('offer_group_id')
    )
    op.create_index(op.f('ix_offer_group_create_at'), 'offer_group', ['create_at'], unique=False)
    op.create_index(op.f('ix_offer_group_name'), 'offer_group', ['name'], unique=True)
    op.create_index(op.f('ix_offer_group_updated_at'), 'offer_group', ['updated_at'], unique=False)
    op.drop_table('service_description')
    op.drop_table('organization_description')
    op.drop_index(op.f('ix_relation_translated_offer_offer_id'), table_name='relation_translated_offer')
    op.drop_index(op.f('ix_relation_translated_offer_offer_type_translation_id'), table_name='relation_translated_offer')
    op.drop_table('relation_translated_offer')
    op.drop_index(op.f('ix_offer_type_translations_code'), table_name='offer_type_translations')
    op.drop_index(op.f('ix_offer_type_translations_language_code'), table_name='offer_type_translations')
    op.drop_index(op.f('ix_offer_type_translations_name'), table_name='offer_type_translations')
    op.drop_table('offer_type_translations')
    op.drop_index(op.f('ix_offer_description_offer_id'), table_name='offer_description')
    op.drop_table('offer_description')
    op.add_column('offers', sa.Column('offer_group_id', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('description', sa.String(), nullable=False))
    op.create_index(op.f('ix_offers_description'), 'offers', ['description'], unique=False)
    op.create_index(op.f('ix_offers_offer_group_id'), 'offers', ['offer_group_id'], unique=False)
    op.create_unique_constraint('unique_offer_service_id', 'offers', ['offer_id', 'service_id'])
    op.create_foreign_key(None, 'offers', 'offer_group', ['offer_group_id'], ['offer_group_id'])
    op.add_column('organization', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('services', sa.Column('description', sa.Text(), nullable=False))
    op.create_index(op.f('ix_services_description'), 'services', ['description'], unique=False)
    op.add_column('user_setup', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_setup', 'date_of_birth')
    op.drop_index(op.f('ix_services_description'), table_name='services')
    op.drop_column('services', 'description')
    op.drop_column('organization', 'description')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint('unique_offer_service_id', 'offers', type_='unique')
    op.drop_index(op.f('ix_offers_offer_group_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_description'), table_name='offers')
    op.drop_column('offers', 'description')
    op.drop_column('offers', 'offer_group_id')
    op.alter_column('engine_types', 'engine_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_table('offer_description',
    sa.Column('description_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name=op.f('offer_description_offer_id_fkey')),
    sa.PrimaryKeyConstraint('description_id', name=op.f('offer_description_pkey')),
    sa.UniqueConstraint('offer_id', 'language_code', name=op.f('uq_offer_description_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_offer_description_offer_id'), 'offer_description', ['offer_id'], unique=False)
    op.create_table('offer_type_translations',
    sa.Column('offer_type_translation_id', sa.INTEGER(), server_default=sa.text("nextval('offer_type_translations_offer_type_translation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('offer_type_translation_id', name='offer_type_translations_pkey'),
    sa.UniqueConstraint('code', 'language_code', name='offer_type_translation_codes', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_offer_type_translations_name'), 'offer_type_translations', ['name'], unique=True)
    op.create_index(op.f('ix_offer_type_translations_language_code'), 'offer_type_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_offer_type_translations_code'), 'offer_type_translations', ['code'], unique=False)
    op.create_table('relation_translated_offer',
    sa.Column('relation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('offer_type_translation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name=op.f('relation_translated_offer_offer_id_fkey')),
    sa.ForeignKeyConstraint(['offer_type_translation_id'], ['offer_type_translations.offer_type_translation_id'], name=op.f('relation_translated_offer_offer_type_translation_id_fkey')),
    sa.PrimaryKeyConstraint('relation_id', name=op.f('relation_translated_offer_pkey')),
    sa.UniqueConstraint('offer_id', 'offer_type_translation_id', name=op.f('uq_offer_translation'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_relation_translated_offer_offer_type_translation_id'), 'relation_translated_offer', ['offer_type_translation_id'], unique=False)
    op.create_index(op.f('ix_relation_translated_offer_offer_id'), 'relation_translated_offer', ['offer_id'], unique=False)
    op.create_table('organization_description',
    sa.Column('description_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], name=op.f('organization_description_organization_id_fkey')),
    sa.PrimaryKeyConstraint('description_id', 'organization_id', name=op.f('organization_description_pkey')),
    sa.UniqueConstraint('organization_id', 'language_code', name=op.f('uq_organization_description_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('service_description',
    sa.Column('description_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name=op.f('service_description_service_id_fkey')),
    sa.PrimaryKeyConstraint('description_id', 'service_id', name=op.f('service_description_pkey')),
    sa.UniqueConstraint('service_id', 'language_code', name=op.f('uq_service_description_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_offer_group_updated_at'), table_name='offer_group')
    op.drop_index(op.f('ix_offer_group_name'), table_name='offer_group')
    op.drop_index(op.f('ix_offer_group_create_at'), table_name='offer_group')
    op.drop_table('offer_group')
    # ### end Alembic commands ###
