"""remove uniqeu index

Revision ID: 91f0d35e22a9
Revises: a425e5d4c701
Create Date: 2025-12-29 01:55:44.045692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f0d35e22a9'
down_revision: Union[str, Sequence[str], None] = 'a425e5d4c701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('offer_type', sa.Enum('MAINTENANCE', 'REPAIR', 'DIAGNOSTICS', 'ELECTRICAL', 'BODY_WORK', name='offertype', native_enum=False, length=50), nullable=False))
    op.drop_index(op.f('ix_offers_name'), table_name='offers')
    op.drop_constraint(op.f('uq_service_id_name_and_car_type'), 'offers', type_='unique')
    op.create_index(op.f('ix_offers_offer_type'), 'offers', ['offer_type'], unique=False)
    op.drop_column('offers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_offers_offer_type'), table_name='offers')
    op.create_unique_constraint(op.f('uq_service_id_name_and_car_type'), 'offers', ['service_id', 'name', 'car_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_offers_name'), 'offers', ['name'], unique=False)
    op.drop_column('offers', 'offer_type')
    # ### end Alembic commands ###
