"""Geometry field for service location

Revision ID: 97270250f438
Revises: 65bd4ec426d2
Create Date: 2026-02-17 01:36:42.545008

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97270250f438'
down_revision: Union[str, Sequence[str], None] = '65bd4ec426d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_car_compatibility', sa.Column('created_at', sa.Integer(), nullable=False))
    op.add_column('offer_car_compatibility', sa.Column('updated_at', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_offer_car_compatibility_created_at'), 'offer_car_compatibility', ['created_at'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_updated_at'), 'offer_car_compatibility', ['updated_at'], unique=False)
    op.add_column('services', sa.Column('location', geoalchemy2.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.create_index('idx_services_location', 'services', ['location'], unique=False, postgresql_using='gist', if_exists=True)
    op.drop_column('services', 'latitude')
    op.drop_column('services', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index('idx_services_location', table_name='services', postgresql_using='gist')
    op.drop_column('services', 'location')
    op.drop_index(op.f('ix_offer_car_compatibility_updated_at'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_created_at'), table_name='offer_car_compatibility')
    op.drop_column('offer_car_compatibility', 'updated_at')
    op.drop_column('offer_car_compatibility', 'created_at')
    # ### end Alembic commands ###
