"""service models extended address

Revision ID: 998c8395eead
Revises: f3d9d4c8fa3a
Create Date: 2025-12-24 19:28:39.264772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "998c8395eead"
down_revision: Union[str, Sequence[str], None] = "f3d9d4c8fa3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("longitude", sa.Float(), nullable=False))
    op.add_column("organization", sa.Column("latitude", sa.Float(), nullable=False))
    op.add_column("organization", sa.Column("original_full_address", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_organization_original_full_address"), "organization", ["original_full_address"], unique=False
    )
    op.add_column("services", sa.Column("longitude", sa.Float(), nullable=False))
    op.add_column("services", sa.Column("latitude", sa.Float(), nullable=False))
    op.add_column("services", sa.Column("original_full_address", sa.String(), nullable=False))
    op.create_index(op.f("ix_services_original_full_address"), "services", ["original_full_address"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_original_full_address"), table_name="services")
    op.drop_column("services", "original_full_address")
    op.drop_column("services", "latitude")
    op.drop_column("services", "longitude")
    op.drop_index(op.f("ix_organization_original_full_address"), table_name="organization")
    op.drop_column("organization", "original_full_address")
    op.drop_column("organization", "latitude")
    op.drop_column("organization", "longitude")
    # ### end Alembic commands ###
