"""car_model - body type

Revision ID: c11e0aa5b9b9
Revises: dab8938fd4bc
Create Date: 2026-06-01 02:20:00.426847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11e0aa5b9b9'
down_revision: Union[str, Sequence[str], None] = 'dab8938fd4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_model', sa.Column('body_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_model', 'body_type')
    # ### end Alembic commands ###
