"""time columns offer_car_compatibility

Revision ID: c75841ebd35e
Revises: 4fdbdeaddc3b
Create Date: 2026-01-02 22:58:28.003427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75841ebd35e'
down_revision: Union[str, Sequence[str], None] = '4fdbdeaddc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_car_compatibility', sa.Column('created_at', sa.Integer(), nullable=False))
    op.add_column('offer_car_compatibility', sa.Column('updated_at', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_offer_car_compatibility_created_at'), 'offer_car_compatibility', ['created_at'], unique=False)
    op.create_index(op.f('ix_offer_car_compatibility_updated_at'), 'offer_car_compatibility', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_car_compatibility_updated_at'), table_name='offer_car_compatibility')
    op.drop_index(op.f('ix_offer_car_compatibility_created_at'), table_name='offer_car_compatibility')
    op.drop_column('offer_car_compatibility', 'updated_at')
    op.drop_column('offer_car_compatibility', 'created_at')
    # ### end Alembic commands ###
