"""car_model - new unique index

Revision ID: dab8938fd4bc
Revises: fab8e29c54b6
Create Date: 2026-06-01 01:58:48.839481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab8938fd4bc'
down_revision: Union[str, Sequence[str], None] = 'fab8e29c54b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('car_model_car_type_name_key'), 'car_model', type_='unique')
    op.create_unique_constraint('uq_car_brand_id_car_type_name', 'car_model', ['car_brand_id', 'car_type_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_car_brand_id_car_type_name', 'car_model', type_='unique')
    op.create_unique_constraint(op.f('car_model_car_type_name_key'), 'car_model', ['car_type_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
