"""engine model - identity always false

Revision ID: e67cc34f3931
Revises: 4363361e4b4f
Create Date: 2026-05-31 01:19:12.674844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67cc34f3931'
down_revision: Union[str, Sequence[str], None] = '4363361e4b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE engine_types ALTER COLUMN engine_id SET GENERATED BY DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE engine_types 
        ALTER COLUMN engine_id ADD GENERATED ALWAYS AS IDENTITY
    """)
    # ### end Alembic commands ###
