"""car brands/types combination

Revision ID: e7c0d0956457
Revises: 97270250f438
Create Date: 2026-02-22 23:58:08.389817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c0d0956457'
down_revision: Union[str, Sequence[str], None] = '97270250f438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_types',
    sa.Column('engine_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('engine_type_id'),
    sa.UniqueConstraint('engine_type_name')
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('car_types', sa.Column('car_brand_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_car_types_car_brand_id'), 'car_types', ['car_brand_id'], unique=False)
    op.create_foreign_key(None, 'car_types', 'car_brands', ['car_brand_id'], ['car_brand_id'])
    op.add_column('offer_car_compatibility', sa.Column('engine_type_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_offer_car_compatibility_car_brand_id'), table_name='offer_car_compatibility')
    op.drop_constraint(op.f('uq_offer_car_type_brand'), 'offer_car_compatibility', type_='unique')
    op.create_index(op.f('ix_offer_car_compatibility_engine_type_id'), 'offer_car_compatibility', ['engine_type_id'], unique=False)
    op.create_unique_constraint('uq_offer_car_type', 'offer_car_compatibility', ['offer_id', 'car_type_id', 'engine_type_id'])
    op.drop_constraint(op.f('offer_car_compatibility_car_brand_id_fkey'), 'offer_car_compatibility', type_='foreignkey')
    op.create_foreign_key(None, 'offer_car_compatibility', 'engine_types', ['engine_type_id'], ['engine_type_id'])
    op.drop_column('offer_car_compatibility', 'car_brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_car_compatibility', sa.Column('car_brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offer_car_compatibility', type_='foreignkey')
    op.create_foreign_key(op.f('offer_car_compatibility_car_brand_id_fkey'), 'offer_car_compatibility', 'car_brands', ['car_brand_id'], ['car_brand_id'])
    op.drop_constraint('uq_offer_car_type', 'offer_car_compatibility', type_='unique')
    op.drop_index(op.f('ix_offer_car_compatibility_engine_type_id'), table_name='offer_car_compatibility')
    op.create_unique_constraint(op.f('uq_offer_car_type_brand'), 'offer_car_compatibility', ['offer_id', 'car_type_id', 'car_brand_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_offer_car_compatibility_car_brand_id'), 'offer_car_compatibility', ['car_brand_id'], unique=False)
    op.drop_column('offer_car_compatibility', 'engine_type_id')
    op.drop_constraint(None, 'car_types', type_='foreignkey')
    op.drop_index(op.f('ix_car_types_car_brand_id'), table_name='car_types')
    op.drop_column('car_types', 'car_brand_id')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_table('engine_types')
    # ### end Alembic commands ###
