"""is_published column in Service model

Revision ID: ea0bd9d4903c
Revises: c75841ebd35e
Create Date: 2026-02-05 23:53:42.625907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0bd9d4903c'
down_revision: Union[str, Sequence[str], None] = 'c75841ebd35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_services_is_published'), 'services', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_is_published'), table_name='services')
    op.drop_column('services', 'is_published')
    # ### end Alembic commands ###
