"""role for user model

Revision ID: ed53342b67bb
Revises: 4dc375e84fc0
Create Date: 2025-11-23 02:46:24.136011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from application.enums.roles import Roles
from application.utils.type_decorators import EnumAsVarchar


# revision identifiers, used by Alembic.
revision: str = 'ed53342b67bb'
down_revision: Union[str, Sequence[str], None] = '4dc375e84fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', EnumAsVarchar(Roles, length=10), nullable=False))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
