"""engine model - rename pk column

Revision ID: f16c6903bb8b
Revises: 8bda5fb2a72c
Create Date: 2026-04-08 01:43:36.214656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16c6903bb8b'
down_revision: Union[str, Sequence[str], None] = '8bda5fb2a72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add new columns first
    op.add_column('engine_types', sa.Column('engine_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('offer_car_compatibility', sa.Column('engine_id', sa.Integer(), nullable=False))
    op.add_column('user_car_relation', sa.Column('engine_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('offer_car_compatibility_engine_type_id_fkey'), 'offer_car_compatibility', type_='foreignkey')
    op.drop_constraint(op.f('user_car_relation_engine_type_id_fkey'), 'user_car_relation', type_='foreignkey')
    op.drop_constraint('engine_types_pkey', 'engine_types', type_='primary')
    op.create_primary_key('engine_types_pkey', 'engine_types', ['engine_id'])
    op.drop_index(op.f('ix_offer_car_compatibility_engine_type_id'), table_name='offer_car_compatibility')
    op.drop_constraint(op.f('uq_offer_car_type'), 'offer_car_compatibility', type_='unique')
    op.drop_index(op.f('ix_user_car_relation_engine_type_id'), table_name='user_car_relation')
    op.create_foreign_key(None, 'offer_car_compatibility', 'engine_types', ['engine_id'], ['engine_id'])
    op.create_foreign_key(None, 'user_car_relation', 'engine_types', ['engine_id'], ['engine_id'])
    op.create_unique_constraint('uq_offer_car_type', 'offer_car_compatibility', ['offer_id', 'car_type_id', 'engine_id'])
    op.create_index(op.f('ix_offer_car_compatibility_engine_id'), 'offer_car_compatibility', ['engine_id'], unique=False)
    op.create_index(op.f('ix_user_car_relation_engine_id'), 'user_car_relation', ['engine_id'], unique=False)
    op.drop_column('engine_types', 'engine_type_id')
    op.drop_column('offer_car_compatibility', 'engine_type_id')
    op.drop_column('user_car_relation', 'engine_type_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_relation', sa.Column('engine_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_car_relation', type_='foreignkey')
    op.create_foreign_key(op.f('user_car_relation_engine_type_id_fkey'), 'user_car_relation', 'engine_types', ['engine_type_id'], ['engine_type_id'])
    op.drop_index(op.f('ix_user_car_relation_engine_id'), table_name='user_car_relation')
    op.create_index(op.f('ix_user_car_relation_engine_type_id'), 'user_car_relation', ['engine_type_id'], unique=False)
    op.drop_column('user_car_relation', 'engine_id')
    op.add_column('offer_car_compatibility', sa.Column('engine_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offer_car_compatibility', type_='foreignkey')
    op.create_foreign_key(op.f('offer_car_compatibility_engine_type_id_fkey'), 'offer_car_compatibility', 'engine_types', ['engine_type_id'], ['engine_type_id'])
    op.drop_index(op.f('ix_offer_car_compatibility_engine_id'), table_name='offer_car_compatibility')
    op.drop_constraint('uq_offer_car_type', 'offer_car_compatibility', type_='unique')
    op.create_unique_constraint(op.f('uq_offer_car_type'), 'offer_car_compatibility', ['offer_id', 'car_type_id', 'engine_type_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_offer_car_compatibility_engine_type_id'), 'offer_car_compatibility', ['engine_type_id'], unique=False)
    op.drop_column('offer_car_compatibility', 'engine_id')
    op.add_column('engine_types', sa.Column('engine_type_id', sa.INTEGER(), server_default=sa.text("nextval('engine_types_engine_type_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('engine_types', 'engine_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
