"""service model created/updated_at default value

Revision ID: f3d9d4c8fa3a
Revises: 78ff8f4f0d7c
Create Date: 2025-12-24 17:25:12.222961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d9d4c8fa3a'
down_revision: Union[str, Sequence[str], None] = '78ff8f4f0d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
