"""car brand - native enum False

Revision ID: fab8e29c54b6
Revises: e67cc34f3931
Create Date: 2026-05-31 02:08:04.288623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fab8e29c54b6'
down_revision: Union[str, Sequence[str], None] = 'e67cc34f3931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_brands', 'country',
               existing_type=postgresql.ENUM('SLOVAKIA', 'CZECHIA', 'AUSTRIA', 'POLAND', 'HUNGARY', name='country'),
               type_=sa.String(20),
               existing_nullable=False)
    op.execute("DROP TYPE IF EXISTS country")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_brands', 'country',
               existing_type=sa.Enum('SK', 'CZ', 'AU', 'PL', 'HU', 'DE', 'IT', 'ES', 'JP', 'KR', 'RO', 'US', 'GB', 'FR', 'SE', 'CN', 'EU', name='country', native_enum=False, length=20),
               type_=postgresql.ENUM('SLOVAKIA', 'CZECHIA', 'AUSTRIA', 'POLAND', 'HUNGARY', name='country'),
               existing_nullable=False)
    # ### end Alembic commands ###
