from enum import Enum


class Groups(Enum):
    ADMIN = "ADMIN"
    MODERATOR = "MODERATOR"

    USER = "USER"
    EXTENDED_USER = "EXTENDED_USER"

    PENDING_SERVICE_ADMIN = "PENDING_SERVICE_ADMIN"
    SERVICE_ADMIN = "SERVICE_ADMIN"
    SERVICE_MASTER = "SERVICE_MASTER"
    SERVICE_MODERATOR = "SERVICE_MODERATOR"
    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
    ORGANIZATION_MASTER = "ORGANIZATION_MASTER"
    ORGANIZATION_MODERATOR = "ORGANIZATION_MODERATOR"
