from enum import Enum


class Groups(Enum):
    USER = "USER"
    EXTENDED_USER = "EXTENDED_USER"
    SERVICE_ADMIN = "SERVICE_ADMIN"
    SERVICE_MASTER = "SERVICE_MASTER"
    SERVICE_MODERATOR = "SERVICE_MODERATOR"
    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
    ORGANIZATION_MASTER = "ORGANIZATION_MASTER"
    ORGANIZATION_MODERATOR = "ORGANIZATION_MODERATOR"
